
# 파이썬 리스트형 자료형

## 1. 리스트형 소개

리스트는 여러 개의 데이터를 하나의 변수에 저장할 수 있는 자료형입니다. **대괄호([])**를 사용하여 생성하며, 서로 다른 자료형도 저장할 수 있습니다.

### 주요 특징
1. **순서가 있다 (Ordered)**: 리스트는 순서를 유지하며, 인덱스를 통해 각 값에 접근할 수 있습니다.
2. **변경 가능 (Mutable)**: 리스트는 생성 후에도 값을 변경할 수 있습니다.
3. **중복 허용**: 동일한 값을 여러 번 포함할 수 있습니다.
4. **다양한 자료형 포함 가능**: 숫자, 문자열, 리스트 등 다양한 자료형을 저장할 수 있습니다.

In [ ]:
# 리스트 예시
x = ["a", "b", "c", "d", "e"]
print(x)

y = [1, 2, 3, ["x", "y"]]
print(y)


## 2. 리스트 생성 및 기본 사용법

### 리스트 생성

In [ ]:
# 빈 리스트 생성
empty_list = []

# 값이 있는 리스트 생성
fruits = ["apple", "banana", "cherry"]
numbers = [1, 2, 3, 4, 5]
mixed = [1, "apple", 3.14, [2, 4, 6]]

print(fruits)   # ['apple', 'banana', 'cherry']
print(numbers)  # [1, 2, 3, 4, 5]
print(mixed)    # [1, 'apple', 3.14, [2, 4, 6]]


## **(3) 리스트 인덱싱과 슬라이싱**

- **인덱싱**: 특정 위치의 값을 가져옴 (0부터 시작).
- **슬라이싱**: 리스트의 일부를 잘라냄.

In [ ]:
# 리스트 인덱싱
fruits = ["apple", "banana", "cherry", "date"]
print(fruits[0])  # apple
print(fruits[-1]) # date (뒤에서 첫 번째)

# 리스트 슬라이싱
print(fruits[1:3])  # ['banana', 'cherry']
print(fruits[:2])   # ['apple', 'banana'] (처음부터 2번째까지)
print(fruits[::2])  # ['apple', 'cherry'] (2칸씩 건너뜀)

## (4) 리스트의 주요 메서드

### **값 추가**

- **`append(value)`**: 리스트의 끝에 값을 추가합니다.
- **`insert(index, value)`**: 특정 위치에 값을 삽입합니다.

In [ ]:
# append 예제
fruits = ["apple", "banana"]
fruits.append("cherry")
print(fruits)  # ['apple', 'banana', 'cherry']

# insert 예제
fruits.insert(1, "orange")
print(fruits)  # ['apple', 'orange', 'banana', 'cherry']

### **값 제거**

- **`remove(value)`**: 지정된 값을 제거합니다.
- **`pop(index)`**: 지정된 인덱스의 값을 제거하고 반환합니다. (인덱스를 생략하면 마지막 값을 제거)
- **`clear()`**: 리스트의 모든 값을 제거합니다.

In [ ]:
# remove 예제
fruits = ["apple", "banana", "cherry", "date"]
fruits.remove("banana")
print(fruits)  # ['apple', 'cherry', 'date']

# pop 예제
last_fruit = fruits.pop() # 뽑
print(last_fruit)  # date
print(fruits)      # ['apple', 'cherry']

# clear 예제
fruits.clear()
print(fruits)  # []

### **값 검색**

- **`index(value)`**: 특정 값의 인덱스를 반환합니다.
- **`count(value)`**: 특정 값이 리스트에 몇 번 등장하는지 반환합니다.

In [ ]:
fruits = ["apple", "banana", "cherry", "apple"]

# index 예제
print(fruits.index("apple"))  # 0 (첫 번째 'apple'의 위치)

# count 예제
print(fruits.count("apple"))  # 2

### **리스트 정렬**

- **`sort()`**: 리스트를 오름차순으로 정렬 (기본값).
- **`reverse()`**: 리스트를 뒤집음.

In [ ]:
numbers = [3, 1, 4, 2]

# sort 예제
numbers.sort()
print(numbers)  # [1, 2, 3, 4]

# reverse 예제
numbers.reverse()
print(numbers)  # [4, 3, 2, 1]

### **리스트 복사**

- **`copy()`**: 리스트를 복사합니다.

In [ ]:
original = [1, 2, 3]
copied = original.copy()

copied.append(4)
print(original)  # [1, 2, 3]
print(copied)    # [1, 2, 3, 4]

## [실습]

### **문제 1: 중복 제거**

- 리스트 `[1, 2, 2, 3, 4, 4, 5]`에서 중복을 제거하고, 고유한 값들만 포함된 리스트를 출력하세요.

### **문제 2: 2차원 리스트**

- 2차원 리스트 `matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]`에서 다음을 수행하세요:
    1. 두 번째 행, 세 번째 열의 값을 출력하세요.
    2. 각 행을 순서대로 출력하세요.

### **문제 3: 리스트 합치기**

- 두 리스트 `list1 = [1, 2, 3]`과 `list2 = [4, 5, 6]`을 합치고, 아래 작업을 수행하세요:
    1. `+` 연산자를 사용하여 합친 결과를 출력하세요.
    2. `extend()` 메서드를 사용하여 `list1`에 `list2`를 추가한 결과를 출력하세요.

### **문제 4: 리스트 컴프리헨션**

- 리스트 컴프리헨션을 사용하여 다음을 수행하세요:
    1. 1부터 10까지의 제곱 값을 포함하는 리스트를 생성하세요.
    2. 1부터 10까지의 숫자 중 짝수만 포함하는 리스트를 생성하세요.

### **문제 5: 리스트 생성 및 접근**

아래 리스트를 생성하고, "banana"와 "date"를 출력하세요:

### **문제 6: 값 추가와 제거**

1. 빈 리스트를 생성하세요.
2. "apple", "banana", "cherry"를 순서대로 추가하세요.
3. "banana"를 제거하세요.

### **문제 7: 리스트 정렬**

- 리스트 `[5, 2, 9, 1, 5, 6]`에서 중복을 제거한 뒤, 오름차순으로 정렬된 결과를 출력하세요.

### **문제 8: 리스트 컴프리헨션 (3의 배수)**

- 1부터 20까지의 숫자 중 3의 배수만 포함하는 리스트를 생성하세요.

### **문제 9: 리스트 확장과 값 추가**

- 두 리스트 `list1 = [1, 2, 3]`과 `list2 = [4, 5, 6]`을 합치고, 마지막에 숫자 `7`을 추가한 결과를 출력하세요.

### **문제 10: 리스트 복사**

- 리스트 `[1, 2, 3]`을 복사한 뒤, 복사본에 숫자 `4`를 추가하세요. 원본 리스트와 복사본을 각각 출력하세요.